/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * API Кинотеатр "Искорка"
 * API Кинотеатр "Искорка"
 * OpenAPI spec version: 1.0.0
 */

export type PutChangeSessionTimeBody = {
  /** Идентификатор фильма */
  idFilm?: number;
  /** Дата сеанса */
  data?: string;
  /** Идентификатор сеанса */
  idSession?: number;
  /** Идентификатор зрительного зала */
  idAuditorium?: number;
  /** Номер места */
  placeNumber?: number;
};
