/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * API Кинотеатр "Искорка"
 * API Кинотеатр "Искорка"
 * OpenAPI spec version: 1.0.0
 */
import type { Pagination } from './pagination';
import type { Seats } from './seats';

export interface SeatsInfo {
  pagination?: Pagination;
  seats: Seats;
}
